package org.example.model;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

/**
 * <pre>
 * CREATE TABLE specialities (
 *     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
 * )
 */
@Entity
@Table(name = "specialties")
@NoArgsConstructor @AllArgsConstructor
@Getter @Setter
@ToString(exclude = { "persons" })
public class Speciality {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @ManyToMany(mappedBy = "specialties")
    @Setter(AccessLevel.PROTECTED)
    private List<Person> persons = new ArrayList<>();
}
