package org.example.model;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * <pre>
 * CREATE TABLE specialities (
 *     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
 * )
 */
@Entity
@Table(name = "specialties")
@NoArgsConstructor @AllArgsConstructor
@Getter @Setter
@ToString(exclude = { "persons" })
public class Speciality {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @ManyToMany(mappedBy = "specialties", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<Person> persons = new ArrayList<>();


    // Utility methods that synchronize both ends whenever another element is added or removed.
    public void addPersons(Collection<Person> persons) {
        persons.forEach(this::addPerson);
    }
    public void addPerson(Person person) {
        person.addSpeciality(this);
    }

    public void removePersons(Collection<Person> persons) {
        persons.forEach(this::removePerson);
    }
    public void removePerson(Person person) {
        person.removeSpeciality(this);
    }
}
