package org.example.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * <pre>
 * CREATE TABLE person_details (
 *     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
 * )
 */
@Entity
@Table(name = "person_details")
@NoArgsConstructor @AllArgsConstructor
@Getter @Setter
@ToString(exclude = { "person" })
public class PersonDetails {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @OneToOne(mappedBy = "personDetails")  // This single annotation makes the association "Bidirectional"
    private Person person;


    // Utility methods that synchronize both ends whenever a child element is added or removed.
    public void setPerson(Person person) {
        person.setPersonDetails(this);
        this.person = person;
    }

    public void removePerson() {
        if (person != null) {
            person.setPersonDetails(null);
            this.person = null;
        }
    }
}
