package org.example.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.BatchSize;

/**
 * <pre>
 * CREATE TABLE persons (
 *     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
 * )
 */
@Entity
@Table(name = "persons")
@BatchSize(size = 20)  // To mitigate "N+1", when "persons" are fetched for "personDetails"
@NoArgsConstructor @AllArgsConstructor
@Getter @Setter
@ToString
public class Person {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @OneToOne(mappedBy = "person", cascade = CascadeType.ALL, orphanRemoval = true)  // This single annotation makes the association "Bidirectional"
    // Results in "N+1" if the "FROM Person" query is executed without "JOIN FETCH" or Entity Graph involved,
    // If you only want to use Static definition tools, there is no workaround to fix "N+1" here.
    private PersonDetails personDetails;


    // Utility methods that synchronize both ends whenever a child element is added or removed.
    public void setPersonDetails(PersonDetails personDetails) {
        this.personDetails = personDetails;
        personDetails.setPerson(this);
    }

    public void removePersonDetails() {
        if (personDetails != null) {
            personDetails.setPerson(null);
            this.personDetails = null;
        }
    }
}
