package org.example.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * <pre>
 * CREATE TABLE persons (
 *     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
 * )
 */
@Entity
@Table(name = "persons")
@NoArgsConstructor @AllArgsConstructor
@Getter @Setter
@ToString
public class Person {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @OneToOne(mappedBy = "person", cascade = CascadeType.ALL, orphanRemoval = true)  // This single annotation makes the association "Bidirectional"
    private PersonDetails personDetails;


    // Utility methods that synchronize both ends whenever a child element is added or removed.
    public void setPersonDetails(PersonDetails personDetails) {
        this.personDetails = personDetails;
        personDetails.setPerson(this);
    }

    public void removePersonDetails() {
        if (personDetails != null) {
            personDetails.setPerson(null);
            this.personDetails = null;
        }
    }
}
