package org.example.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * <pre>
 * CREATE TABLE persons (
 *     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     speciality_id INTEGER NOT NULL,
 *     FOREIGN KEY (speciality_id) REFERENCES specialties
 * )
 */
@Entity
@Table(name = "persons")
@NoArgsConstructor @AllArgsConstructor
@Getter @Setter
@ToString
public class Person {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    // Means "FOREIGN KEY (speciality_id) REFERENCES specialties"
    @ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })  // Use PERSIST only if "speciality" has no unique constraints
    @JoinColumn(name = "speciality_id")  // Optional, mostly used to just specify the column name (as in @Column)
    private Speciality speciality;
}
