package org.example.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * <pre>
 * CREATE TABLE person_details (
 *     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
 * )
 */
@Entity
@Table(name = "person_details")
@NoArgsConstructor @AllArgsConstructor
@Getter @Setter
@ToString
public class PersonDetails {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
}
