package org.example.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * <pre>
 * CREATE TABLE persons (
 *     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     person_details_id INTEGER NOT NULL UNIQUE,
 *     FOREIGN KEY (person_details_id) REFERENCES person_details
 * )
 */
@Entity
@Table(name = "persons")
@NoArgsConstructor @AllArgsConstructor
@Getter @Setter
@ToString
public class Person {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    // Means "FOREIGN KEY (person_details_id) REFERENCES person_details(id)"
    @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @JoinColumn(name = "person_details_id")  // Optional, mostly used to just specify the column name (as in @Column)
    private PersonDetails personDetails;
}
