package org.example.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * <pre>
 * CREATE TABLE person_details (
 *     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     person_id INTEGER NOT NULL UNIQUE,
 *     FOREIGN KEY (person_id) REFERENCES persons
 * )
 */
@Entity
@Table(name = "person_details")
@NoArgsConstructor @AllArgsConstructor
@Getter @Setter
@ToString
public class PersonDetails {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    // Means "FOREIGN KEY (person_id) REFERENCES persons(id)"
    @OneToOne(optional = false)
    @JoinColumn(name = "person_id")  // Optional, mostly used to just specify the column name (as in @Column)
    private Person person;
}
